### ISSUE TITLE
Add hover effect to reset button

### ISSUE THREAD

**Issue by hardeepnarang10** [hardeepnarang10/keyboard-pro#1]
The `#reset` button, aka the `Start Over` button at present doesn't transition to hover state as illustrated in the README. It must have the following hover properties:

The background color must switch to *orangered* on mouse over.
The color of the button text must turn *white* on mouse over.

Also, this issue must be resolved using pure CSS and NOT Javascript.
Good luck!

**Comment by prahuljose** [comment]
hey @hardeepnarang10 , i can try this!

**Comment by codenarocode** [comment]
Hello @hardeepnarang10 sir . I am going to add this feature.

**Comment by Prachi-05** [comment]
#8 I've added the hover feature to this button

**Comment by hardeepnarang10** [comment]
Solved with commit c50dd94ca45db75b1b139d8a2effe69b6b966ef7
Thanks everybody for submissions and for participating in this discussion.
