### ISSUE TITLE
perf: border-width of test-area to be increased

### ISSUE THREAD

**Issue by prahuljose** [hardeepnarang10/keyboard-pro#4]
hey @hardeepnarang10, was looking over your code functionality and had added the appropriate event listeners, I had noticed that while typing, the change in the UI to inform that I have typed something incorrectly wasn't as _eye-catching_, I'd suggest increasing the following code from  `border-width: 5px;` to `border-width: 15px;`.
<br>

_PFB the earlier UI:_
![image](https://user-images.githubusercontent.com/24572086/135503970-e5e45984-eb2f-4af1-a954-5b079e94f416.png)

_PFB the revised UI:_
![image](https://user-images.githubusercontent.com/24572086/135503762-2e9059ef-4aeb-442b-a1cc-cfd51d282f6c.png)

**Comment by hardeepnarang10** [comment]
Personally, border-width at `7.5px` and above is too out-of-place for me. I'd be willing to accept a value at `7px` max.

**Comment by hardeepnarang10** [comment]
@prahuljose can you make a submission on this?
I'll be closing this issue if no submissions are received by the end of the month.
